language: cpp
os: linux
dist: trusty
script: make unittests && ./unittests 
sudo: required
services:
  - docker
before_install:
  - docker pull redis
  - docker run -p 127.0.0.1:6379:6379 -d redis
  - eval "${MATRIX_EVAL}"
matrix:
  include:
    - compiler:
      - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-test1.55-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - compiler:
      - clang
      addons:
        apt:
          packages:
            - clang-4.0
            - libboost-test1.55-dev 
          sources:
            - llvm-toolchain-trusty-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
